pipeline{
    agent any
    stages{
        stage('code'){
            steps{
                git url:'https://github.com/Tandon77ayush/two-tier-flask-app.git'
            }
        }
        stage('build'){
            steps{
                sh 'docker build -t flask-app .'
            }
        }
        stage('docker push'){
            steps{
            withCredentials([usernamePassword(
                credentialsId: 'dockerhubred',
                usernameVariable: 'USERNAME',
                passwordVariable: 'PASSWORD'
                )]){
                    sh 'docker login -u $USERNAME -p $PASSWORD'
                }
            }
        }
        stage('deploy'){
            steps{
                sh 'docker compose up -d'
            }
        }
        
    }
}
